name: mambaflow

target:
  _target_: scripts.network.models.mambaflow.MambaFlow
  voxel_size: ${voxel_size}
  point_cloud_range: ${point_cloud_range}
  num_frames: ${num_frames}

val_monitor: val/Dynamic/Mean